// build.js - Static Site Generator for Environment Variables
require('dotenv').config();
const fs = require('fs');
const path = require('path');

console.log("🛠️ Starting Build Process...");

// 1. Load Safe Environment Variables
const clientEnvVars = {};
const safePrefixes = ['FIREBASE_', 'VITE_', 'PUBLIC_', 'REACT_APP_']; // Add prefixes you want to expose

Object.keys(process.env).forEach(key => {
    // We expose variables that match our safe prefixes, 
    // OR specifically in this project, we know we need FIREBASE config.
    // For backwards compatibility with the previous server.js, we were exposing all of them.
    // However, for security on a static host, let's just expose FIREBASE related ones
    // and any explicitly marked PUBLIC_
    if (key.startsWith('FIREBASE_') || key.startsWith('PUBLIC_') || key === 'PORT') {
        clientEnvVars[key] = process.env[key];
    }
});

// 2. Generate the JS content
const envConfigJS = `// Auto-generated by build.js for Static Hosting - DO NOT EDIT\nwindow.ENV = ${JSON.stringify(clientEnvVars, null, 2)};\n`;

// 3. Write to root directory as env-config.js (where index.html expects it)
const outputPath = path.join(__dirname, 'env-config.js');

try {
    fs.writeFileSync(outputPath, envConfigJS, 'utf8');
    console.log(`✅ Successfully generated: ${outputPath}`);
    console.log(`📦 Exported ${Object.keys(clientEnvVars).length} environment variables.`);

    if (process.env.FIREBASE_PROJECT_ID) {
        console.log(`🔥 Target Firebase Project: ${process.env.FIREBASE_PROJECT_ID}`);
    } else {
        console.warn(`⚠️ Warning: FIREBASE_PROJECT_ID is missing from environment!`);
    }

} catch (error) {
    console.error(`❌ Failed to write env-config.js:`, error);
    process.exit(1);
}

console.log("🎉 Build step completed successfully.");
