// Auto-generated by build.js for Static Hosting - DO NOT EDIT
window.ENV = {
  "FIREBASE_API_KEY": "AIzaSyDeAvREXEottX1_jyFV2sCamSHW7DgW6AE",
  "FIREBASE_APP_ID": "1:382205577494:web:a99580da8b60ba945e6837",
  "FIREBASE_AUTH_DOMAIN": "smart-manager-by-abhi.firebaseapp.com",
  "FIREBASE_DATABASE_URL": "https://smart-manager-by-abhi-default-rtdb.asia-southeast1.firebasedatabase.app",
  "FIREBASE_MEASUREMENT_ID": "G-E9FG4W9LHT",
  "FIREBASE_MESSAGING_SENDER_ID": "382205577494",
  "FIREBASE_PROJECT_ID": "smart-manager-by-abhi",
  "FIREBASE_STORAGE_BUCKET": "smart-manager-by-abhi.firebasestorage.app"
};
