// server.js - Serves the app and injects environment variables
require('dotenv').config();
const express = require('express');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// --- Load Environment Variables for Client ---
// Filter out sensitive keys if necessary, or just send everything that is safe
const clientEnvVars = {};
Object.keys(process.env).forEach(key => {
    // Basic filtering: You might want to be more selective here in production
    // For now, we replicate previous behavior of sending everything found in .env
    // except strictly internal system variables if any.
    // If you have specific prefixes like PUBLIC_ or REACT_APP_, filter by those.
    // Here we just copy everything for compatibility with previous logic,
    // assuming .env only contained safe-to-expose config or the user handles it.
    clientEnvVars[key] = process.env[key];
});

// --- Generate the env-config.js content ---
const envConfigJS = `// Auto-generated by server.js - DO NOT EDIT
window.ENV = ${JSON.stringify(clientEnvVars, null, 2)};
`;

// --- Routes ---

// Serve the dynamically generated env-config.js
app.get('/env-config.js', (req, res) => {
    res.set('Content-Type', 'text/javascript');
    res.send(envConfigJS);
});

// Serve static files from the root directory
app.use(express.static(__dirname));

// Fallback for SPA (if needed in future, otherwise basic static serve covers index.html)
// For now, we just let express.static handle '/', 'index.html', etc.

// --- Start Server ---
app.listen(PORT, () => {
    console.log(`\n  ✅ Smart Manager Server running at:`);
    console.log(`     http://localhost:${PORT}\n`);
    console.log(`  📦 Environment: ${Object.keys(clientEnvVars).length} variables loaded`);
    console.log(`  🔥 Firebase Project: ${process.env.FIREBASE_PROJECT_ID || 'NOT SET'}\n`);
});
